# Generated by Django 3.2.9 on 2022-08-01 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_two', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentaccount',
            name='customer',
        ),
        migrations.AddField(
            model_name='currentaccount',
            name='customer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_account', to='task_two.customer'),
        ),
    ]
