# Generated by Django 3.2.9 on 2022-08-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_two', '0002_auto_20220801_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentaccount',
            old_name='customer_account',
            new_name='customer',
        ),
    ]
