# Generated by Django 3.2.9 on 2022-08-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_two', '0003_rename_customer_account_currentaccount_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentaccount',
            old_name='customer',
            new_name='customer_account',
        ),
    ]
