# Generated by Django 3.2.9 on 2022-08-01 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_two', '0004_rename_customer_currentaccount_customer_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaccount',
            name='customer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_two.customer'),
        ),
    ]
