# Generated by Django 3.2.9 on 2022-08-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_two', '0008_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaccount',
            name='customer_account',
            field=models.IntegerField(unique=True),
        ),
    ]
